browser=chrome
url=https://adactinhotelapp.com/HotelAppBuild2/

valid.username=shreemathi
valid.password=Swetha@13#

invalid.username=wronguser
invalid.password=wrongpass

register.url=https://adactinhotelapp.com/Register.php

fullname=Shreemathi
email=rjshreemathi@gmail.com

first.name=Shreemathi
last.name=Rajesh
address=Chennai Tamil Nadu

card.number=4111111111111111
invalid.card.number=12345

card.type=VISA
card.exp.month=January
card.exp.year=2030

cvv=123
invalid.cvv=12

location=Sydney
room.type=Standard
room.count=1 - One
adults=2 - Two
children=1 - One